<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NSubstitute" Version="6.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WitnessPuzzles.Infrastructure\WitnessPuzzles.Infrastructure.csproj" />
    <ProjectReference Include="..\WitnessPuzzles.Core\WitnessPuzzles.Core.csproj" />
    <ProjectReference Include="..\WitnessPuzzles.Application\WitnessPuzzles.Application.csproj" />
    <ProjectReference Include="..\WitnessPuzzles.Api\WitnessPuzzles.Api.csproj" />
  </ItemGroup>

</Project>